**Experiment 12: Implement and Evaluate a Hidden Markov Model using hmmlearn for Sequential Pattern Recognition.**

**Aim:** To implement and evaluate a Hidden Markov Model (HMM) using the Python library hmmlearn in order to model sequential data and perform pattern recognition based on probabilistic state transitions.

**Overview of Hidden Markov Model (HMM)**

A **Hidden Markov Model (HMM)** is a statistical model used for **sequential or time-series data** where the system follows the **Markov property** (the current state depends only on the previous state).

In an HMM:

* The system has **hidden states** that cannot be directly observed.
* Each hidden state generates **observable outputs**.
* The model learns **state transition probabilities** and **observation probabilities**.

HMMs are useful when the **underlying process is hidden but observations are visible**.

---

**Key Components**

**1. Hidden States (S)**
Set of possible internal states of the system.

S = {S1, S2, ..., SN}

---

**2. Observations (O)**
Visible outputs produced by hidden states.

O = {O1, O2, ..., OT}

---

**3. Transition Probability Matrix (A)**
Probability of moving from one state to another.

a_ij = P(q_t+1 = Sj | q_t = Si)

Where
Si → current state
Sj → next state

---

**4. Emission Probability Matrix (B)**
Probability of observing a symbol given a hidden state.

b_j(k) = P(O_t = Vk | q_t = Sj)

Where
Vk → observation value

---

**5. Initial State Probability (π)**
Probability that the system starts in a particular state.

pi_i = P(q1 = Si)

---

**Model Representation**

An HMM is defined as:

lambda = (A, B, pi)

Where
**A** = Transition probabilities
**B** = Emission probabilities
**π** = Initial state probabilities

**Installation and Imports**

In [3]:
!pip install hmmlearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 4.3 MB/s eta 0:00:00


In [5]:
import numpy as np
from hmmlearn import hmm

**Network Intrusion Detection**


**Hidden States and Observations**

Hidden states represent the true network condition, which is not directly observable.

**Hidden States**

S1: Normal Traffic, S2: Suspicious Activity, S3: Intrusion Attack

**Observations**

Observable indicators from network monitoring.

O1: Low Packet Rate, O2: Moderate Packet Rate, O3: High Packet Rate

**Mapping for coding:**

Low Packet Rate → 0

Moderate Packet Rate → 1

High Packet Rate → 2

In [6]:
# Define Hidden States & Observations
states = ["S1", "S2", "S3"]
observations = ["O1", "O2", "O3"]

# Define Initial State Probabilities
start_propabilities = np.array([0.33, 0.33, 0.34])

# Define Transition Probabilities
transition_propabilities = np.array([
    [0.7, 0.2, 0.1], # Normal
    [0.3, 0.4, 0.3], # Suspicious
    [0.2, 0.3, 0.5] # Intrusion
])

# Define Emission Probabilities
emission_propabilities = np.array([
    [0.7, 0.25, 0.05], # Normal
    [0.2, 0.6, 0.2], # Suspicious
    [0.05, 0.25, 0.7] # Intrusion
])

# Create Observation Sequence
# Example network packet activity:
# Low → Moderate → Moderate → High → High → Moderate → Low

observations = np.array([[0], [1], [1], [2], [2], [1], [0]])

**Build the Hidden Markov Model:** Disable automatic training so the model uses the defined probabilities.

In [7]:
model = hmm.CategoricalHMM(n_components=3, init_params="", params="")

# Set the model parameters
model.startprob_ = start_propabilities
model.transmat_ = transition_propabilities
model.emissionprob_ = emission_propabilities

**Decode Most Likely Hidden State Sequence (Viterbi)**

In [8]:
logprob, hidden_states = model.decode(observations, algorithm="viterbi")

print("Most Likely Hidden States:", hidden_states)

Most Likely Hidden States: [0 1 1 2 2 1 0]


In [9]:
 # Map states to names
state_names = ["Normal", "Suspicious", "Intrusion"]
decoded_states = [state_names[state] for state in hidden_states]
print(decoded_states)

['Normal', 'Suspicious', 'Suspicious', 'Intrusion', 'Intrusion', 'Suspicious', 'Normal']


**Compute Sequence Likelihood:** Higher likelihood indicates the sequence fits the model well.

In [10]:
log_likelihood = model.score(observations)

print("Log Likelihood of Observation Sequence:", log_likelihood)

Log Likelihood of Observation Sequence: -7.742762348186395


**Posterior Probability of States:** Each row represents probability of the system being in each hidden state at that time step.

In [11]:
posterior_prob = model.predict_proba(observations)

print("Posterior State Probabilities:")
print(posterior_prob)

Posterior State Probabilities:
[[0.66215449 0.27247837 0.06536714]
 [0.3180957  0.53391161 0.1479927 ]
 [0.1513309  0.57512342 0.27354568]
 [0.03157508 0.19546978 0.77295515]
 [0.04178957 0.19353802 0.76467241]
 [0.27478057 0.5024914  0.22272803]
 [0.7362322  0.21173951 0.05202829]]


**Generate Sample Sequence**

Generate artificial sequences from the model.

model.sample() generates sequences randomly according to the probability distributions defined in the HMM. Therefore, the generated observations and hidden states may differ each time the program is executed.

In [12]:
X, Z = model.sample(8)

print("Generated Observations:", X.flatten())

print("Generated Hidden States:", Z)

Generated Observations: [2 1 1 0 1 2 1 0]
Generated Hidden States: [2 2 0 0 1 1 0 1]


**Conclusion**

A Hidden Markov Model was successfully implemented using hmmlearn to model sequential patterns in network traffic. The model decoded hidden system states using the Viterbi algorithm, computed posterior state probabilities, evaluated sequence likelihood, and generated synthetic sequences. This demonstrates how HMMs can be applied to sequential pattern recognition tasks such as network intrusion detection.