**Experiment 1: Introduction to required python libraries such as Numpy, Pandas, Scipy, Matplotlib and Scikit-learn.**

**Aim**

To understand the basics of essential Python libraries used in Machine Learning such as NumPy, Pandas, SciPy, Matplotlib, and Scikit-learn, and to learn how they are used for data handling, computation, visualization, and simple machine learning tasks.


**NumPy Library**

NumPy is a Python library used for working with numbers and numerical data. It provides support for arrays and matrices and allows us to perform mathematical operations on large amounts of data easily and efficiently. NumPy is mainly used for calculations, data storage in array form, and scientific computing in Machine Learning.

**Importing NumPy**

NumPy is imported to perform numerical operations using arrays.

In [1]:
import numpy as np

**1D Array in NumPy**

**Creating a 1D Array:** A 1D array stores multiple values in a single line.

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)
arr

[10 20 30 40 50]


array([10, 20, 30, 40, 50])

**Accessing Elements:** Elements are accessed using index positions starting from 0.

In [3]:
print(arr[0])   # First element
print(arr[3])   # Fourth element

10
40


**Array Length:** Find the number of elements in the array.

In [4]:
print(len(arr))

5


**Basic Operations on 1D Array**


Arithmetic operations are applied to all elements at once.

In [5]:
print(arr + 5)
print(arr - 2)
print(arr * 2)
print(arr / 2)

[15 25 35 45 55]
[ 8 18 28 38 48]
[ 20  40  60  80 100]
[ 5. 10. 15. 20. 25.]


**Mathematical Functions:** NumPy provides built-in mathematical functions.

In [6]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

150
30.0
50
10


**Changing Array Values:** Modify elements using index positions.

In [7]:
arr[2] = 100
print(arr)

[ 10  20 100  40  50]


**Array Data Type:** Check the type of elements stored in the array.

In [8]:
print(arr.dtype)

int64


**Properties of 1D NumPy Array**


**Size of Array:** Size gives the total number of elements in the array.

In [9]:
print(arr.size)

5


**Number of Dimensions:** It shows how many dimensions the array has.

In [10]:
print(arr.ndim)

1


**Shape of Array:** Shape shows the structure of the array.

In [11]:
print(arr.shape)

(5,)


**Slicing in 1D Array**

**Basic Slicing:** Slicing is used to extract a part of the array.

In [12]:
print(arr[1:4])   # From index 1 to 3

[ 20 100  40]


**Slicing from Beginning:** If starting index is not given, slicing starts from 0.

In [13]:
print(arr[:3])

[ 10  20 100]


**Slicing till End:** If ending index is not given, slicing goes till last element.

In [14]:
print(arr[2:])

[100  40  50]


**Negative Indexing:** Negative index accesses elements from the end.

In [15]:
print(arr[-1])
print(arr[-3:])

50
[100  40  50]


**Iterating Through 1D Array**

**Using for Loop:** Looping through each element.

In [16]:
for i in arr:
    print(i)

10
20
100
40
50


**Copying a 1D Array**

**Copy Method:** Creates a separate copy of the array.

In [17]:
arr_copy = arr.copy()
arr_copy[0] = 999
print(arr)
print(arr_copy)

[ 10  20 100  40  50]
[999  20 100  40  50]


**Reshaping 1D Array**

**Reshape to 2D:** Convert 1D array into 2D form.

In [18]:
new_arr = arr.reshape(1, 5)
print(new_arr)

[[ 10  20 100  40  50]]


**Checking Array Type**

**Type of Variable:** Confirms it is a NumPy array.



In [19]:
print(type(arr))

<class 'numpy.ndarray'>


**2D Arrays in NumPy**

**Creating a 2D Array:** A 2D array stores data in rows and columns.

In [20]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


**Accessing Elements in 2D Array:** Access elements using row and column index.

In [21]:
print(arr2d[0, 1])   # Element in 1st row, 2nd column

2


**Size of 2D Array**

In [22]:
print(arr2d.size)

6


**Number of Dimensions**

In [23]:
print(arr2d.ndim)

2


**Shape of 2D Array**

In [24]:
print(arr2d.shape)

(2, 3)


**Slicing in 2D Array**

In [25]:
print(arr2d[:, 1])    # All rows, second column
print(arr2d[0, :])    # First row

[2 5]
[1 2 3]


**Iterating Through 2D Array**

In [26]:
for row in arr2d:
    for element in row:
        print(element)

1
2
3
4
5
6


**NumPy Array Creation Functions**

**Zeros Array:** Creates an array filled with zeros.

In [27]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


**Ones Array:** Creates an array filled with ones.

In [28]:
o = np.ones(4)
print(o)

[1. 1. 1. 1.]


**Arange Function:** Creates values within a range.

In [29]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


**Linspace Function:** Creates evenly spaced values.

In [30]:
l = np.linspace(1, 10, 5)
print(l)

[ 1.    3.25  5.5   7.75 10.  ]


**Comparison and Boolean Operations**

**Comparison Operators:** Used to compare array values.

In [31]:
arr = np.array([10, 20, 30, 40, 50])
print(arr > 25)
print(arr == 20)

[False False  True  True  True]
[False  True False False False]


**Boolean Indexing:**Extract elements based on condition.

In [32]:
print(arr[arr > 25])

[30 40 50]


**Logical Operations**

In [33]:
print(np.logical_and(arr > 15, arr < 45))
print(np.logical_or(arr < 15, arr > 45))

[False  True  True  True False]
[ True False False False  True]


**Random Numbers in NumPy**

**Random Integer Values**

In [34]:
r1 = np.random.randint(1, 100, 5)
print(r1)

[65 90 96 59  4]


**Random Float Values**

In [35]:
r2 = np.random.rand(5)
print(r2)

[0.29080952 0.97542187 0.65973884 0.92086132 0.84402931]


**Random 2D Array**

In [36]:
r3 = np.random.rand(2, 3)
print(r3)

[[0.17839354 0.86279949 0.96174005]
 [0.14679274 0.21592365 0.92214198]]


**Setting Seed Value:** Ensures same random output every time.

In [37]:
np.random.seed(10)
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]


**Shuffle:** Shuffle randomly changes the order of elements in the same array.

In [38]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 3 2 1 4]


**Choice:** Choice selects random elements from an array.

In [39]:
arr = np.array([10, 20, 30, 40, 50])
c = np.random.choice(arr)
print(c)

10


**Choice with Multiple Values:** Select more than one random value.

In [40]:
c2 = np.random.choice(arr, size=3)
print(c2)

[20 30 10]


**Choice with Replacement:** Allows repeated values.

In [41]:
c3 = np.random.choice(arr, size=5, replace=True)
print(c3)

[20 10 30 10 50]


**Choice without Replacement:** Each value is selected only once.

In [42]:
c4 = np.random.choice(arr, size=5, replace=False)
print(c4)

[30 20 50 10 40]


**Permutation:** Returns a new shuffled array without changing original.

In [43]:
arr = np.array([1, 2, 3, 4, 5])
p = np.random.permutation(arr)
print(p)
print(arr)

[5 2 1 3 4]
[1 2 3 4 5]


**Random Sample:** Generates random float values between 0 and 1.

In [44]:
s = np.random.random(4)
print(s)

[0.19812181 0.03061665 0.87761494 0.72743551]


**Random Normal Distribution:** Generates values following normal distribution.

In [45]:
n = np.random.normal(0, 1, 5)
print(n)

[-1.08684028  0.12055902  1.40202525 -0.4342591  -1.25424191]


**Random Uniform Distribution:** Generates values within a given range.

In [46]:
u = np.random.uniform(10, 20, 5)
print(u)

[18.26082248 11.05401833 12.83576679 10.65563266 10.56444187]
